# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
#Solution
import numpy as np

age = input('Please input your age:')
ar=np.random.randint(10,age,int(age))
print('Printing',age,'numbers between the range 10 to',age,':')
print(ar)




Please input your age:45
Printing 45 numbers between the range 10 to 45 :
[13 30 17 13 42 43 11 20 16 17 27 35 18 13 19 34 16 20 40 14 16 14 30 32
 25 16 29 40 16 18 12 42 35 29 27 35 35 29 17 43 29 13 16 12 30]


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
# Solution
ar = np.arange(1,50,2)
print('Elements in the Array:',ar)
print('Length of the numpy array ar is:',len(ar))




Elements in the Array: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Length of the numpy array ar is: 25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
# Solution
ar = np.linspace(4,7,27)
print('Elements of Array are:\n',ar)



Elements of Array are:
 [4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
# Solution
ar= np.random.rand(5,4).round(2)
print('Elements of a 5 x 4 array rounded off to two decimal places:\n\n',ar)


Elements of a 5 x 4 array rounded off to two decimal places:

 [[0.32 0.7  0.72 0.45]
 [0.59 0.67 0.89 0.74]
 [0.12 0.26 0.56 0.63]
 [0.03 0.42 0.28 1.  ]
 [0.36 0.87 0.31 0.7 ]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
# Solution

ar= np.random.randint(5,15,(5,5))
print('Elements of a 5 x 5 array of integers between 5 and 15:\n\n',ar)


Elements of a 5 x 5 array of integers between 5 and 15:

 [[14  5 10 11  9]
 [ 6  9  9 14 14]
 [ 7 10 10 11  5]
 [12 10 14  8  9]
 [10  9 14  7 12]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [40]:
# Solution
ar= np.random.randint(0,20)
print('Random value:',ar)
ar=np.zeros((ar,), dtype=int)
print('\n',ar)



Random value: 10

 [0 0 0 0 0 0 0 0 0 0]


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [42]:
# Solution
ar_row= np.random.randint(1,5)
ar_column= np.random.randint(1,5)
print('Random no. of rows and columns are:',ar_row,',',ar_column)
ar=np.ones((ar_row,ar_column), dtype=float)
print('\n',ar)



Random no. of rows and columns are: 2 , 4

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [43]:
# Solution
matrix1 = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,5,6],[23,12,8,5,8]])
print('Given matrix:\n',matrix1)
print('\nShape of the Matrix:',matrix1.shape)
print('\nType:',type(matrix1))
print('\ndtype:',matrix1.dtype)


Given matrix:
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6  5  6]
 [23 12  8  5  8]]

Shape of the Matrix: (5, 5)

Type: <class 'numpy.ndarray'>

dtype: int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [45]:
# Solution
import math 

mrows = len(matrix1)
mcolumns = len(matrix1[0])

print('Given matrix:\n',matrix1)
print('\nNo. of Rows:',mrows)
print('No. of Columns:',mcolumns)
print('Center element of the given matrix is:',matrix1[math.floor(mrows/2)][math.floor(mcolumns/2)])



Given matrix:
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6  5  6]
 [23 12  8  5  8]]

No. of Rows: 5
No. of Columns: 5
Center element of the given matrix is: 3


#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
# Solution
print('3rd Row elements:',matrix1[2])



3rd Row elements: [ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
# Solution
print('4th Column elements:',matrix1[:,3])



4th Column elements: [34 65 76  5  5]


#### 12. Print the 4 corner pixels of the matrix

In [47]:
# Solution
mrows = len(matrix1)
mcolumns = len(matrix1[0])

print('Given matrix:\n',matrix1)
print('\nCorner elements of the given matrix:',matrix1[0][0],matrix1[0][mcolumns-1],matrix1[mrows-1][0],matrix1[mrows-1][mcolumns-1])



Given matrix:
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6  5  6]
 [23 12  8  5  8]]

Corner elements of the given matrix: 9 45 23 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [48]:
# Solution 
m1 = matrix1[0:2,2:4]
print('Matrix m1:\n', m1)
m2 = matrix1[3:5,0:2]
print('\nMatrix m2:\n', m2)
m3 = matrix1[2:5,2:5]
print('\nMatrix m3:\n', m3)

Matrix m1:
 [[50 34]
 [34 65]]

Matrix m2:
 [[ 7  8]
 [23 12]]

Matrix m3:
 [[ 3 76  3]
 [ 6  5  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [49]:
# Solution
print('Matrix m1:\n', m1)
m11 = m1.reshape(1,m1.size)
print('One Dimeensional vector m1:\n',m11)

print('\nMatrix m2:\n', m2)
m21 = m2.reshape(1,m2.size)
print('One Dimeensional vector m2:\n',m21)

print('\nMatrix m3:\n', m3)
m31 = m3.reshape(1,m3.size)
print('One Dimeensional vector m3:\n',m31)


Matrix m1:
 [[50 34]
 [34 65]]
One Dimeensional vector m1:
 [[50 34 34 65]]

Matrix m2:
 [[ 7  8]
 [23 12]]
One Dimeensional vector m2:
 [[ 7  8 23 12]]

Matrix m3:
 [[ 3 76  3]
 [ 6  5  6]
 [ 8  5  8]]
One Dimeensional vector m3:
 [[ 3 76  3  6  5  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [50]:
# Solution
print('Matrix m1:\t\t\tMatrix m2:')
print(m1[0,:],'\t\t\t',m2[0,:])
print(m1[1,:],'\t\t\t',m2[1,:])

horizontal_matrix = np.concatenate((m1, m2), axis=1)
print('\nHorizontal Concatenation:\n',horizontal_matrix)

vertical_matrix = np.concatenate((m1, m2), axis=0)
print('\nVertical Concatenation:\n',vertical_matrix)



Matrix m1:			Matrix m2:
[50 34] 			 [7 8]
[34 65] 			 [23 12]

Horizontal Concatenation:
 [[50 34  7  8]
 [34 65 23 12]]

Vertical Concatenation:
 [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [51]:
# Solution
print('Matrix m1:\t\t\tMatrix m2:')
print(m1[0,:],'\t\t\t',m2[0,:])
print(m1[1,:],'\t\t\t',m2[1,:])
print('\nMatrix Addition: m1 + m2')
print(np.add(m1,m2))

print('\nMatrix Subtraction: m1 - m2')
print(np.subtract(m1,m2))

print('\nMatrix Multiplication: m1 * m2')
print(np.multiply(m1,m2))

print('\nMatrix Division: m1 / m2')
print(np.divide(m1,m2).round(2))



Matrix m1:			Matrix m2:
[50 34] 			 [7 8]
[34 65] 			 [23 12]

Matrix Addition: m1 + m2
[[57 42]
 [57 77]]

Matrix Subtraction: m1 - m2
[[43 26]
 [11 53]]

Matrix Multiplication: m1 * m2
[[350 272]
 [782 780]]

Matrix Division: m1 / m2
[[7.14 4.25]
 [1.48 5.42]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [52]:
# Solution
print('Matrix m3:\n',m3)
m3 = np.delete(np.delete(m3,0,axis=0),2,axis=1)

print('\nMatrix m3 after removing first row and last column:\n',m3)

print('\nMatrix m1:\t\t\tMatrix m3:')
print(m1[0,:],'\t\t\t',m3[0,:])
print(m1[1,:],'\t\t\t',m3[1,:])
print('\nMatrix Addition: m1 + m3')
print(np.add(m1,m3))



Matrix m3:
 [[ 3 76  3]
 [ 6  5  6]
 [ 8  5  8]]

Matrix m3 after removing first row and last column:
 [[6 5]
 [8 5]]

Matrix m1:			Matrix m3:
[50 34] 			 [6 5]
[34 65] 			 [8 5]

Matrix Addition: m1 + m3
[[56 39]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [53]:
# Solution
print('Matrix m1:')
print(m1)

m1_Mean = np.mean(m1,axis=1)
print('\nMatrix m1_Mean:')
print(m1_Mean)
print('\nShape of m1_Mean matrix:',m1_Mean.shape)
m1_Mean = m1_Mean.reshape(1,2)
print('\nm1_Mean matrix is Reshaped to:',m1_Mean.shape)

m4 = np.concatenate((m1, m1_Mean), axis=0)
print('\nConcat matrices m1 and m1_Mean to get matrix m4:\n',m4)



Matrix m1:
[[50 34]
 [34 65]]

Matrix m1_Mean:
[42.  49.5]

Shape of m1_Mean matrix: (2,)

m1_Mean matrix is Reshaped to: (1, 2)

Concat matrices m1 and m1_Mean to get matrix m4:
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [54]:
# Solution
m4_temp = m4
m4 = m4.T
print('Matrix m3:\t\tMatrix m4:\t\tTransposed Matrix m4:')
print(m3[0,:],'\t\t\t',m4_temp[0,:],'\t\t',m4[0,:])
print(m3[1,:],'\t\t\t',m4_temp[1,:],'\t\t',m4[1,:])
print('\t\t\t',m4_temp[2,:])

print('\nMatrix Multiplication: m3 * m4.T')
print(np.dot(m3,m4))


Matrix m3:		Matrix m4:		Transposed Matrix m4:
[6 5] 			 [50. 34.] 		 [50. 34. 42.]
[8 5] 			 [34. 65.] 		 [34.  65.  49.5]
			 [42.  49.5]

Matrix Multiplication: m3 * m4.T
[[470.  529.  499.5]
 [570.  597.  583.5]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [55]:
# Solution
print('Original Matrix:\n',matrix1)

print('\n\t\t\t Min\t\t Max')
print('\nMean\t\t\t',np.ndarray.mean(matrix1,axis=1).min(),'\t\t',np.ndarray.mean(matrix1,axis=1).max())
print('Standard Deviation\t',np.ndarray.std(matrix1,axis=1).min().round(2),'\t\t',np.ndarray.std(matrix1,axis=1).max().round(2))
print('Variance\t\t',np.ndarray.var(matrix1,axis=1).min().round(4),'\t\t',np.ndarray.var(matrix1,axis=1).max().round(4))





Original Matrix:
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6  5  6]
 [23 12  8  5  8]]

			 Min		 Max

Mean			 6.4 		 32.6
Standard Deviation	 1.02 		 28.64
Variance		 1.04 		 820.16


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [57]:
# Solution 
import numpy as np

runs_scored = np.array([['MSD',54,60,10,65],
                       ['Kholi',102,2,78,32],
                       ['Rohit',3,110,1,92],
                       ['Rahul',56,6,12,42],
                       ['Dhawan',12,8,22,11]])
print('Runs Scored in 4 Matches:\n',runs_scored)

balls_faced = np.array([['MSD',50,42,22,78],
                       ['Kholi',95,8,65,43],
                       ['Rohit',9,100,7,101],
                       ['Rahul',27,3,11,31],
                       ['Dhawan',24,20,36,27]])
print('\nBalls Faced in 4 Matches:\n',balls_faced)


# temp array to store runs_scored and balls_faced as float values

player_runs = (runs_scored[0:,1:]).astype(float)
balls_count = (balls_faced[0:,1:]).astype(float)


# finding Average for each player, shaping to 5,1 matrix and 
# concating to first column of 'runs_scored' np array
Average_runs = np.ndarray.mean(player_runs,axis = 1)
Average_runs = Average_runs.reshape(5,1)
runs_average = np.concatenate((runs_scored[0:,0].reshape(5,1),Average_runs.astype(float)),axis = 1)
print('\nAverage Runs Scored by Players:\n',runs_average)

#convert the 'runs_average' list into array and 
#use sorted function to sort Players Average in descending order
runs_average = np.array(runs_average)
runs_average = np.array(sorted(runs_average,key=lambda x:float(x[1]),reverse = True))

print('\nPlayers Average in Descending order:\n',runs_average)


# finding Strike rate for each player, shaping to 5,1 matrix 
# and concating to first column of 'runs_scored' np array
Total_runs = np.ndarray.sum(player_runs,axis = 1)
Total_runs = Total_runs.reshape(5,1)

Total_balls = np.ndarray.sum(balls_count,axis = 1)
Total_balls = Total_balls.reshape(5,1)

Strike = ((Total_runs.astype(float)/Total_balls.astype(float)) * 100).round(2)
Strike = np.array(Strike)
           
Strike_rate = np.concatenate((balls_faced[0:,0].reshape(5,1),Strike.astype(float)),axis = 1)
print('\nStrike Rate for each Players:\n',Strike_rate)

#convert the 'Strike_rate' list into array and 
#use sorted function to sort Players Strike_rate in descending order
Strike_rate = np.array(Strike_rate)
Strike_rate = np.array(sorted(Strike_rate,key=lambda x:float(x[1]),reverse = True))

print('\nStrike Rate for Players in Descending order:\n',Strike_rate)

Runs Scored in 4 Matches:
 [['MSD' '54' '60' '10' '65']
 ['Kholi' '102' '2' '78' '32']
 ['Rohit' '3' '110' '1' '92']
 ['Rahul' '56' '6' '12' '42']
 ['Dhawan' '12' '8' '22' '11']]

Balls Faced in 4 Matches:
 [['MSD' '50' '42' '22' '78']
 ['Kholi' '95' '8' '65' '43']
 ['Rohit' '9' '100' '7' '101']
 ['Rahul' '27' '3' '11' '31']
 ['Dhawan' '24' '20' '36' '27']]

Average Runs Scored by Players:
 [['MSD' '47.25']
 ['Kholi' '53.5']
 ['Rohit' '51.5']
 ['Rahul' '29.0']
 ['Dhawan' '13.25']]

Players Average in Descending order:
 [['Kholi' '53.5']
 ['Rohit' '51.5']
 ['MSD' '47.25']
 ['Rahul' '29.0']
 ['Dhawan' '13.25']]

Strike Rate for each Players:
 [['MSD' '98.44']
 ['Kholi' '101.42']
 ['Rohit' '94.93']
 ['Rahul' '161.11']
 ['Dhawan' '49.53']]

Strike Rate for Players in Descending order:
 [['Rahul' '161.11']
 ['Kholi' '101.42']
 ['MSD' '98.44']
 ['Rohit' '94.93']
 ['Dhawan' '49.53']]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [58]:
# Solution

marks=np.array([65,84,47,56,89,98,48,77,80,39])
passed = ((marks[:] >= 50).sum())
print('Total no. of Students:',len(marks))
print('No. of Students Passed:',passed)
print('No. of Students yet to Pass:',len(marks) - passed)

Total no. of Students: 10
No. of Students Passed: 7
No. of Students yet to Pass: 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [59]:
# Solution

print('Students Original Mark list:',marks)
gracelist = np.where((marks > 44) & (marks < 50))
marks[gracelist] = marks[gracelist] + 5

a_gradelist = np.where((marks > 80) & (marks < 95))
marks[a_gradelist] =  marks[a_gradelist] + 5

o_gradelist = np.where((marks > 94))
marks[o_gradelist] =  100
print('Students Marks after adding grace marks:',marks)



Students Original Mark list: [65 84 47 56 89 98 48 77 80 39]
Students Marks after adding grace marks: [ 65  89  52  56  94 100  53  77  80  39]


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [60]:
import numpy as np
import sys 
import time

#Executing funciton using LIST

xlist = range(1,60001)
ylist = range(1,60001)

start_listtime = time.time()

result_list = [((xlist[i]**2 + 8)/ylist[i]) for i in range(0,60000)]
end_listtime = time.time()

print('Time taken to execute given Function using list:',(end_listtime - start_listtime) * 1000)


#Executing function using NUMPY Array

x_range = np.arange(1,60001)
y_range = np.arange(1,60001)

start_npytime = time.time()

result_npy = [((x_range[i].astype(np.int64)**2 + 8)/y_range[i].astype(np.int64)) for i in range(0,60000)]
end_npytime = time.time()

print('\nTime taken to execute given Function using Numpy array:',(end_npytime - start_npytime) * 1000)


Time taken to execute given Function using list: 39.98422622680664

Time taken to execute given Function using Numpy array: 37.1861457824707


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [73]:
# A Github account was created and the solution was uploaded in the following site location
# https://github.com/botaiguru/SRM

# Github A/C name: botaiguru

# About Numpy
print('Find the Soluition of the Lab Exercise in the following link in GITHUB :')
print('https://github.com/botaiguru/SRM')

print("\nNUMPY in Python")
print("================")
print('\nNumPy is a Numerical library for Python programming language that supports large, multi-dimensional arrays and matrices, enabling numerous high level mathematical functions to manipulate data stored in arrays.')

print('\nNumPy is an Open-source software that has gone through several modifications since its inception in 1995 by several of its contributors who designed & developed it until 2005 and then released another version in 2006 as well.')

print('\nNumPy uses non-optimizing bytecode interpreter which is slower than some compiler equivalents. However, NumPy enables multi-dimensional array functionalities with "ndarray" for n-dimensional array data structure.')

print('\nUnlike Python’s Lists, inserting or appending entries into a NumPy array is unlikely and the system gets around these operations by creating new copy of the arrays in operation. Using NumPy for vectorization may also increase memory complexity as copies of input data are created for data manipulation. Other open-source solutions are available to overcome such problems of NumPy.\n')



Find the Soluition of the Lab Exercise in the following link in GITHUB :
https://github.com/botaiguru/SRM

NUMPY in Python

NumPy is a Numerical library for Python programming language that supports large, multi-dimensional arrays and matrices, enabling numerous high level mathematical functions to manipulate data stored in arrays.

NumPy is an Open-source software that has gone through several modifications since its inception in 1995 by several of its contributors who designed & developed it until 2005 and then released another version in 2006 as well.

NumPy uses non-optimizing bytecode interpreter which is slower than some compiler equivalents. However, NumPy enables multi-dimensional array functionalities with "ndarray" for n-dimensional array data structure.

Unlike Python’s Lists, inserting or appending entries into a NumPy array is unlikely and the system gets around these operations by creating new copy of the arrays in operation. Using NumPy for vectorization may also increas